name: Update Lapras Career

on:
  push:
    branches:
      - main
    paths:
      - 'CAREER.ts'

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install Dependencies
      run: bun install --frozen-lockfile

    - name: Run Command
      env:
        MY_EMAIL_ADDRESS: ${{ secrets.MY_EMAIL_ADDRESS }}
        MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
      run: bun run exec
